<a href="https://colab.research.google.com/github/junio-firmino/Aprendizado_python/blob/master/soccer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd

In [6]:
data = '/content/drive/MyDrive/soccer.csv'

In [11]:
players = pd.read_csv(data)

In [13]:
players.head()

                name     club  age  ... club_id  big_club  new_signing
0     Alexis Sanchez  Arsenal   28  ...       1         1            0
1         Mesut Ozil  Arsenal   28  ...       1         1            0
2          Petr Cech  Arsenal   35  ...       1         1            0
3       Theo Walcott  Arsenal   28  ...       1         1            0
4  Laurent Koscielny  Arsenal   31  ...       1         1            0

[5 rows x 17 columns]

In [18]:
players.position.unique()

array(['LW', 'AM', 'GK', 'RW', 'CB', 'RB', 'CF', 'LB', 'DM', 'RM', 'CM',
       nan, 'SS', 'LM'], dtype=object)

In [20]:
players.shape

(465, 17)

In [22]:
players.position.isin(['LB'])

0      False
1      False
2      False
3      False
4      False
       ...
460    False
461     True
462    False
463    False
464    False
Name: position, Length: 465, dtype: bool

In [25]:
players.loc[players.position.isin(['LB'])]

                      name               club  ...  big_club new_signing
7            Nacho Monreal            Arsenal  ...         1           0
18            Kieran Gibbs            Arsenal  ...         1           0
29          Sead Kolasinac            Arsenal  ...         1           0
34         Charlie Daniels        Bournemouth  ...         0           0
54              Brad Smith        Bournemouth  ...         0           0
62             Gaetan Bong  Brighton+and+Hove  ...         0           0
65          Markus Suttner  Brighton+and+Hove  ...         0           0
82            Stephen Ward            Burnley  ...         0           0
99   Marcos Alonso Mendoza            Chelsea  ...         1           1
112                 Kenedy            Chelsea  ...         1           0
119    Patrick van Aanholt     Crystal+Palace  ...         0           0
128        Jeffrey Schlupp     Crystal+Palace  ...         0           0
134            Pape Souare     Crystal+Palace  ...         0           0
138        Leighton Baines            Everton  ...         0           0
168             Chris Lowe       Huddersfield  ...         0           0
175           Scott Malone       Huddersfield  ...         0           0
196        Christian Fuchs     Leicester+City  ...         0           0
212           Ben Chilwell     Leicester+City  ...         0           0
236         Alberto Moreno          Liverpool  ...         1           0
251     Aleksandar Kolarov    Manchester+City  ...         1           0
270            Daley Blind  Manchester+United  ...         1           0
281              Luke Shaw  Manchester+United  ...         1           0
294           Paul Dummett   Newcastle+United  ...         0           0
298       Massadio Haidara   Newcastle+United  ...         0           0
312          Ryan Bertrand        Southampton  ...         0           0
328           Matt Targett        Southampton  ...         0           0
336           Erik Pieters         Stoke+City  ...         0           0
354             Josh Tymon         Stoke+City  ...         0           0
363          Martin Olsson            Swansea  ...         0           0
369       Stephen Kingsley            Swansea  ...         0           0
389             Ben Davies          Tottenham  ...         1           0
390             Danny Rose          Tottenham  ...         1           0
403           Jose Holebas            Watford  ...         0           0
455        Aaron Cresswell           West+Ham  ...         0           0
461         Arthur Masuaku           West+Ham  ...         0           1

[35 rows x 17 columns]

In [26]:
len(players.loc[players.position.isin(['LB'])])

35

In [29]:
players.get(players.position.isin(['LB']))

                      name               club  ...  big_club new_signing
7            Nacho Monreal            Arsenal  ...         1           0
18            Kieran Gibbs            Arsenal  ...         1           0
29          Sead Kolasinac            Arsenal  ...         1           0
34         Charlie Daniels        Bournemouth  ...         0           0
54              Brad Smith        Bournemouth  ...         0           0
62             Gaetan Bong  Brighton+and+Hove  ...         0           0
65          Markus Suttner  Brighton+and+Hove  ...         0           0
82            Stephen Ward            Burnley  ...         0           0
99   Marcos Alonso Mendoza            Chelsea  ...         1           1
112                 Kenedy            Chelsea  ...         1           0
119    Patrick van Aanholt     Crystal+Palace  ...         0           0
128        Jeffrey Schlupp     Crystal+Palace  ...         0           0
134            Pape Souare     Crystal+Palace  ...         0           0
138        Leighton Baines            Everton  ...         0           0
168             Chris Lowe       Huddersfield  ...         0           0
175           Scott Malone       Huddersfield  ...         0           0
196        Christian Fuchs     Leicester+City  ...         0           0
212           Ben Chilwell     Leicester+City  ...         0           0
236         Alberto Moreno          Liverpool  ...         1           0
251     Aleksandar Kolarov    Manchester+City  ...         1           0
270            Daley Blind  Manchester+United  ...         1           0
281              Luke Shaw  Manchester+United  ...         1           0
294           Paul Dummett   Newcastle+United  ...         0           0
298       Massadio Haidara   Newcastle+United  ...         0           0
312          Ryan Bertrand        Southampton  ...         0           0
328           Matt Targett        Southampton  ...         0           0
336           Erik Pieters         Stoke+City  ...         0           0
354             Josh Tymon         Stoke+City  ...         0           0
363          Martin Olsson            Swansea  ...         0           0
369       Stephen Kingsley            Swansea  ...         0           0
389             Ben Davies          Tottenham  ...         1           0
390             Danny Rose          Tottenham  ...         1           0
403           Jose Holebas            Watford  ...         0           0
455        Aaron Cresswell           West+Ham  ...         0           0
461         Arthur Masuaku           West+Ham  ...         0           1

[35 rows x 17 columns]

In [30]:
len(players.get(players.position.isin(['LB'])))

35